import numpy as np

a = np.array([33,44,54,23,25,55,32,76])
print(np.average(a))

a = a.reshape(2,4)
print(a)
print(np.average(a))
print(np.average(a, axis=0))
print(np.average(a, axis=1))
b = np.random.rand(24).reshape(2,3,4)
print(b)
print()
print(np.average(b, axis=0))
print()
print(np.average(b, axis=1))
print()
print(np.average(b, axis=2))
a = a.flatten()
w = np.array([0.1,0.05,0.2,0.0,0.0,0.4,0.2,0.05])
print(np.average(a, weights=w))
w2 = np.array([0.2,0.8])
a = a.reshape(2,4)
print(a)
print(np.average(a, axis=0, weights=w2))
print(np.average(a, returned="True"))
a = a.flatten()
print(a)
print()
print(w)
print(np.average(a,weights=w, returned="True"))
np.random.seed(1)
a = np.random.randint(0,10,20)
print(a)
print()
print(np.mean(a))
print()
print(a.mean())
b = a.reshape(4,5)
print(b)
print(np.mean(b))
print(b.mean())
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))
c = np.random.rand(24).reshape((2,3,4))
print(c)
print(np.mean(c, axis=0))
print(np.mean(c, axis=1))
print(np.mean(c, axis=2))
print(b)
e = np.mean(b, keepdims=True)
print(e)
print(e.shape)
f = np.mean(b, keepdims=False)
print(f)
g = np.mean(b, axis=1, keepdims=True)
print(g)
print(g.shape)
h = np.mean(b, axis=1, keepdims=False)
print(h)
print(h.shape)





